name: PR Checks
runs-on: node:20-alpine

on: pull_request

jobs:
  verify-code-standards:
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Prettier
        run: npx prettier --check ./src

  verify-build:
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build
